[tool.poetry]
name = "pythonQEPest"
version = "1.0.0"
description = ""
authors = ["Lina <knocker767@gmail.com>"]
readme = "README.md"
packages = [
    { include = "pythonQEPest" }
]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
pydantic = "2.7.1"


[build-system]
requires = ["poetry-core>=1.0.0", "setuptools>=40.8.0"]
build-backend = "poetry.core.masonry.api"
