[project]
name = "pythonQEPest"
version = "2.0.0a5"
description = "Java QEPest but written in Python"
readme = "README.md"
requires-python = ">=3.12,<3.15"
authors = [{ name = "Lina", email = "knocker767@gmail.com" }]
dependencies = ["pydantic==2.12.5", "python-dotenv>=1.2.1,<2.0.0", "ruff (>=0.15.18,<0.16.0)"]

[project.optional-dependencies]
gui = ["pyperclip>=1.11.0,<2.0.0"]
rdkit = ["rdkit (>=2024.3.1,<2026.0.0)"]

[project.scripts]
pythonqepest = "pythonQEPest.cli.cli:main"

[project.gui-scripts]
pythonqepest-gui = "pythonQEPest.gui.gui:main"

[tool.poetry]
packages = [{ include = "pythonQEPest" }]

[dependency-groups]
dev = [
    "pytest (>=9.1.1)",
    "pre-commit (>=4.6.0,<5.0.0)",
    "pyinstaller (>=6.21.0,<7.0.0)",
    "poethepoet[poetry_plugin] (>=0.46.0)",
    "pytest-cov (>=7.0.0,<8.0.0)",
    "twine (>=6.2.0,<7.0.0)",
]

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools>=40.8.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88
exclude = [".venv", ".git", "__pycache__", "build", "dist"]

[tool.ruff.lint]
select = ["E", "F", "W", "B", "C4", "UP"]
ignore = ["E203"]

[tool.ruff.format]
quote-style = "double"

[tool.poe.tasks]
test = "pytest"
build-simple = "pyinstaller --onefile pythonQEPest/main.py"
build-gui = "pyinstaller --onefile --noconsole pythonQEPest/gui/gui.py"
publish-pypi = "twine upload --repository pythonQEPest dist/*"
